services:
  zeeter:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
        SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    ports:
      - "${APP_PUBLIC_PORT}:4173"
    env_file:
      - .env
